DAN/DAN/DAN/Models/Order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long Id { get; set; }
        public string Prefix { get; set; }
        public string OId { get; set; }
        public string Fullname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public decimal TotalPrice { get; set; }
        public string Code { get; set; }
        public System.DateTime CreatOn { get; set; }
        public bool Status { get; set; }
        public string PaidInfo { get; set; }
        public bool Paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

DAN/DAN/DAN/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAN.Models;
using System.Data.Entity.Validation;
using System.Data.Entity;
using System.Configuration;

namespace DAN.Controllers
{
    public class OrderController : Controller
    {
        DANEntities db = new DANEntities();
        [HttpGet]
        public ActionResult Index()
        {
            var model = new OrderViewModel();
            if (Session["Cart"] == null)
                return RedirectToAction("Index", "Cart");
            if (Session["User"] != null)
            {
                model = (OrderViewModel)Session["User"];
                return View(model);
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Confirm(OrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Code != null)
                {
                    var code = db.Codes.SingleOrDefault(e => e.Code1 == model.Code);
                    if (code == null || code.Expired.Value)
                    {
                        ModelState.AddModelError("Code", "Mã khuyến mãi không hợp lệ hoặc đã được sử dụng!");
                        return View("Index");
                    }
                }
                Session["User"] = model;
                return View(model);
            }

            return View("Index");
        }
        private void setDataVnPay(long OId,string PaidInfo,decimal Amount)
        {
            DateTime dateTime = DateTime.Now;
            Int32 now =(Int32)DateTime.UtcNow.Subtract(new DateTime(dateTime.Year, dateTime.Month,dateTime.Day)).TotalSeconds;
            string vnp_Returnurl = ConfigurationManager.AppSettings["vnp_Returnurl"]; //URL nhan ket qua tra ve 
            string vnp_Url = ConfigurationManager.AppSettings["vnp_Url"]; //URL thanh toan cua VNPAY 
            string vnp_TmnCode = ConfigurationManager.AppSettings["vnp_TmnCode"]; //Ma website
            string vnp_HashSecret = ConfigurationManager.AppSettings["vnp_HashSecret"]; //Chuoi bi mat

            VnPayLibrary vnpay = new VnPayLibrary();

            vnpay.AddRequestData("vnp_Version", "2.0.0");
            vnpay.AddRequestData("vnp_Command", "pay");
            vnpay.AddRequestData("vnp_TmnCode", vnp_TmnCode);

            string locale = "vn";
            if (!string.IsNullOrEmpty(locale))
            {
                vnpay.AddRequestData("vnp_Locale", locale);
            }
            else
            {
                vnpay.AddRequestData("vnp_Locale", "vn");
            }

            vnpay.AddRequestData("vnp_CurrCode", "VND");
            vnpay.AddRequestData("vnp_TxnRef", now + OId.ToString());
            vnpay.AddRequestData("vnp_OrderInfo", PaidInfo);
            vnpay.AddRequestData("vnp_OrderType", "100001"); //default value: other
            vnpay.AddRequestData("vnp_Amount", (Convert.ToInt64(Amount)* 100).ToString());
            vnpay.AddRequestData("vnp_ReturnUrl", vnp_Returnurl);
            vnpay.AddRequestData("vnp_IpAddr", Utils.GetIpAddress());
            vnpay.AddRequestData("vnp_CreateDate", dateTime.ToString("yyyyMMddHHmmss"));

            string paymenturl = vnpay.CreateRequestUrl(vnp_Url, vnp_HashSecret);
            Response.Redirect(paymenturl);

        }

        //public ActionResult ReturnPayMent()
        //{
        //    if (checkpayment() == true)
        //    {
        //        return RedirectToAction("ReturnVNPay");
        //        //return View("KetQua");
        //    }
        //    return RedirectToAction("Index");

        //}
        VnPayLibrary vnpay = new VnPayLibrary();

      
        public ActionResult ReturnPayMent()
        {
            string error = "Thanh toán không thành công!";
            if (Request.QueryString.Count > 0)
            {
                string dataAsString = Request.Cookies["StoreCookies"].Value;
                List<string> data = new List<string>();
                data.AddRange(dataAsString.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries));
                string vnp_HashSecret = ConfigurationManager.AppSettings["vnp_HashSecret"]; //Chuoi bi mat
                var vnpayData = Request.QueryString;

                //if (vnpayData.Count > 0)
                //{
                foreach (string s in vnpayData)
                {
                    //get all querystring data
                    if (!string.IsNullOrEmpty(s) && s.StartsWith("vnp_"))
                    {
                        vnpay.AddResponseData(s, vnpayData[s]);
                    }
                }
                // }

                //vnp_TxnRef: Ma don hang merchant gui VNPAY tai command=pay    
                long orderId = Convert.ToInt64(vnpay.GetResponseData("vnp_TxnRef"));
                //vnp_TransactionNo: Ma GD tai he thong VNPAY
                long vnpayTranId = Convert.ToInt64(vnpay.GetResponseData("vnp_TransactionNo"));
                //vnp_ResponseCode:Response code from VNPAY: 00: Thanh cong, Khac 00: Xem tai lieu
                string vnp_ResponseCode = vnpay.GetResponseData("vnp_ResponseCode");
                //vnp_SecureHash: MD5 cua du lieu tra ve
                String vnp_SecureHash = Request.QueryString["vnp_SecureHash"];
                bool checkSignature = vnpay.ValidateSignature(vnp_SecureHash, vnp_HashSecret);
                if (checkSignature)
                {
                    var user = (OrderViewModel)Session["User"];
                    var cart = (List<Product>)Session["Cart"];
                    if (vnp_ResponseCode == "00")
                    {
                        var order = new Order()
                        {
                            Prefix = "BTA-",
                            Fullname = data[0],
                            Address = data[1],
                            Phone = data[2],
                            Email = data[3],
                            Code = data[4],
                            Status = true,
                            Paid = true,
                            CreatOn = DateTime.Now,
                            TotalPrice = Convert.ToDecimal(data[5]),
                            PaidInfo = data[6]
                        };

                        db.Orders.Add(order);
                        db.SaveChanges();
                        foreach (var item in cart)
                        {
                            db.OrderDetails.Add(new OrderDetail()
                            {
                                Pname = item.Pname,
                                OId = order.Id,
                                Quantum = item.Quantum,
                                Price = item.Quantum * item.SalePrice
                            });

                            db.SaveChanges();
                        }

                        long OId = db.Orders.Max(x => x.Id);

                        var result = db.Orders.First(x => x.Id == OId);

                        Session.Remove("Cart");
                        return View("ReturnVNPay", result);
                    }
                    else
                    {
                        return View("ReturnVNPay");
                    }
                }
                else
                {
                    return View("ReturnVNPay");
                }
            }
            else
            {
                return View("ReturnVNPay");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Done()
        {
            var user = (OrderViewModel)Session["User"];
            var cart = (List<Product>)Session["Cart"];
            try
            {
                var order = new Order()
                {
                    Prefix = "BTA-",
                    Fullname = user.fullName,
                    Address = user.adress,
                    Phone = user.phone.ToString(),
                    Email = user.email,
                    Code = user.Code ?? "Không sử dụng",
                    CreatOn = DateTime.Now,
                    TotalPrice = cart.Sum(e => e.Quantum * e.SalePrice),
                    PaidInfo = user.PaidInfo
                };
                HttpCookie httpCookie = new HttpCookie("StoreCookies");
                DateTime now = DateTime.Now;

                // Set the cookie value.
                List<String> listData = new List<string>();
                listData.Add(user.fullName);
                listData.Add(user.adress);
                listData.Add(user.phone.ToString());
                listData.Add(user.email);
                listData.Add(user.Code ?? "Không sử dụng");
                listData.Add(cart.Sum(e => e.Quantum * e.SalePrice).ToString());
                listData.Add(user.PaidInfo);
                string dataAsString = listData.Aggregate((a, b) => a = a + "," + b);
                httpCookie.Value = dataAsString;
                // Set the cookie expiration date.
                httpCookie.Expires = now.AddSeconds(180); // For a cookie to effectively never expire

                // Add the cookie.
                Response.Cookies.Add(httpCookie);
                setDataVnPay(order.Id, user.PaidInfo, cart.Sum(e => e.Quantum * e.SalePrice));
                //bool checkSignature = vnpay.ValidateSignature(secureHash, hashSecret);
                //db.Orders.Add(order);
                //db.SaveChanges();
                //foreach (var item in cart)
                //{
                //    db.OrderDetails.Add(new OrderDetail()
                //    {
                //        Pname = item.Pname,
                //        OId = order.Id,
                //        Quantum = item.Quantum,
                //        Price = item.Quantum * item.SalePrice
                //});
                    
                //    db.SaveChanges();

DAN/DAN/DAN/Views/Order/Confirm.cshtml
@model DAN.Models.OrderViewModel
@{
    ViewBag.Title = "Xác nhận đơn hàng";
}
<div class="container">
    <div class="row info">
        <div class="title">Xác nhận đơn hàng</div>
        <div class="checkout">
            <div class="confirm">
                Xin chào bạn <b>@Model.fullName</b><br />
                Chúng tôi đã nhận được thông tin đặt hàng của bạn. Xin vui lòng kiểm tra lại thông tin dưới đây một lần nữa<br />
                Họ tên: <b>@Model.fullName</b><br />
                Địa chỉ nhận hàng: <b>@Model.adress</b><br />
                Số điện thoại: <b>@Model.phone</b><br />
                Hình thức thanh toán: <b>@Model.PaidInfo</b><br />
                @if (Model.email != null)
                {
                    @: Hóa đơn sẽ được gửi vào email <b>@Model.email</b><br />
                }
                Tổng giá trị đơn hàng: <b style="color: red;">@String.Format("{0:0,0}", ((List<DAN.Models.Product>)Session["Cart"]).Sum(e => e.Quantum * e.Price)) VND</b>
                @using (Html.BeginForm("Done", "Order"))
                {
                    @Html.AntiForgeryToken()
                    <button>XÁC NHẬN ĐƠN HÀNG</button> <a href="/Order">QUAY LẠI</a>
                }
            </div>
        </div>
    </div>
</div>

DAN/DAN/DAN/Views/Order/Done.cshtml
@model DAN.Models.Order
@{
    ViewBag.Title = "Hoàn thành đặt hàng";
}
<div class="container">
    <div class="row info">
        <div class="checkout">
            <div class="confirm">
                Cảm ơn bạn đã đặt hàng. Mã đơn hàng của bạn là <b>@Model?.Id</b><br />
                Kiểm tra đơn hàng của bạn tại: <a href="http://localhost:49278/Order/SearchInvoice">http://localhost:49278/Order/SearchInvoice</a><br />
                Bạn có thể liên hệ hotline: <b>0354122468</b> để chúng tôi duyệt đơn hàng cho bạn sớm nhất có thể.<br />
                Xin cảm ơn!
            </div>
        </div>
    </div>
</div>

DAN/DAN/DAN/Views/Order/Index.cshtml
@model DAN.Models.OrderViewModel

@{
    ViewBag.Title = "Tiến hành đặt hàng";
}
<div class="container">
    <div class="row info">
        <div class="title ">Tiến hành đặt hàng</div>
        @using (Html.BeginForm("Confirm", "Order", FormMethod.Post, new { @class = "my-form" }))
        {
    <div class="col-md-6 col-sm-6 col-xs-12">
     

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.LabelFor(e => e.fullName)
            @Html.ValidationMessageFor(e => e.fullName)
            @Html.TextBoxFor(e => e.fullName, new { @value = Session["User"] != null ? Model.fullName : "" })

            @Html.LabelFor(e => e.adress)
            @Html.ValidationMessageFor(e => e.adress)
            @Html.TextBoxFor(e => e.adress, new { @value = Session["User"] != null ? Model.adress : "" })

            @Html.LabelFor(e => e.phone)
            @Html.ValidationMessageFor(e => e.phone)
            @Html.TextBoxFor(e => e.phone, new { @value = Session["User"] != null ? Model.phone : 0 })

            @Html.LabelFor(e => e.email)
            @Html.ValidationMessageFor(e => e.email)
            @Html.TextBoxFor(e => e.email, new { @value = Session["User"] != null ? Model.email : "" })

            @Html.LabelFor(e => e.Code)
            @Html.ValidationMessageFor(e => e.Code)
            @Html.TextBoxFor(e => e.Code)
        
        <button>ĐẶT HÀNG NGAY</button>
    </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <label>Phương thức thanh toán</label>
                <div class="checkout">
                    <div class="payment-type">
                        @Html.RadioButtonFor(e => e.PaidInfo, "Thanh toán online", new { @checked = "true" })
                        <span>Thanh toán online</span>
                    </div>
                    @*<div class="payment-type">
                        @Html.RadioButtonFor(e => e.PaidInfo,"COD - Thanh toán khi nhận hàng")
                        <span>COD - Thanh toán khi nhận hàng</span>
                    </div>*@
                    <div class="payment-type">
                        <span>Tổng đơn hàng: <b style="color: red">@String.Format("{0:0,0}", ((List<DAN.Models.Product>)Session["Cart"]).Sum(e => e.Quantum * e.Price)) VND</b></span>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

DAN/DAN/DAN/Views/Order/Invoice.cshtml
@model DAN.Models.InvoiceViewModel
@{
    //ViewBag.Title = "Đơn hàng - " + Model.order?.OId;
    //var paid = Model.order.Paid ? "<b style=\"color:green\">Đã thanh toán</b>" : "<b style=\"color:red\">Chưa thanh toán</b>";
    //var status = Model.order.Status ? "<b style=\"color:green\">Đã hoàn thành</b>" : "<b style=\"color:red\">Chưa hoàn thành</b>";
    var i = 1;
}
<div class="container">
    <div class="row info">
        <div class="title">thông tin chi tiết: @Model.order.OId</div>
        <div class="col-md3 col-sm-6 col-xs-12">
            Mã đơn hàng: <b>@Model.order.OId</b><br />
            Tổng giá trị: <b>@String.Format("{0:0,0}", Model.order.TotalPrice) VND</b><br />
            @*Thanh toán: @Html.Raw(paid)<br />
            Tình trạng: @Html.Raw(status)<br />*@
            Hình thức thanh toán: @Model.order.PaidInfo
        </div>
        <div class="col-md-6 hidden-xs"></div>
        <div class="col-md3 col-sm-6 col-xs-12">
            Khách hàng: <b>@Model.order.Fullname</b><br />
            Địa chỉ nhận hàng: <b>@Model.order.Address</b><br />
            SĐT: <b>@Model.order.Phone</b>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="title">chi tiết sản phẩm</div>
            @if (Model.orderDetail.Count() == 0)
            {
                <div class="error">Lỗi, không tải được sản phẩm</div>
            }
            else
            {
                <table align="center" border="1" cellspacing="0">
                    <tr><th>STT</th><th>Tên SP</th><th>Số lượng</th><th>Thành tiền</th></tr>
                    @foreach (var item in Model.orderDetail)
                    {
                        <tr><td>@i</td><td>@item.Pname</td><td>@item.Quantum</td><td>@String.Format("{0:0,0}", item.Price)</td></tr>
                        i++;
                    }
                </table>
            }
        </div>
        @*<div class="col-md-12 col-sm-12 col-xs-12">
            @if (User.Identity.IsAuthenticated)
            {
                if (!Model.order.Status)
                {
                    using (Html.BeginForm("Invoice", "Order", new { returnUrl = "/Order/Invoice/"+Model.order.OId },FormMethod.Post, new { @class = "my-form" }))
                    {
                        @Html.Hidden("key","status")
                        @Html.Hidden("OId", Model.order.OId)
                        <button>DUYỆT ĐƠN HÀNG NÀY</button>
                    }
                }
                if (!Model.order.Paid)
                {
                    using (Html.BeginForm("Invoice", "Order", new { returnUrl = "/Order/Invoice/" + Model.order.OId }, FormMethod.Post, new { @class = "my-form" }))
                    {
                        @Html.Hidden("key", "paid")
                        @Html.Hidden("OId", Model.order.OId)
                        <button>XÁC NHẬN ĐƠN NÀY ĐÃ THANH TOÁN</button>
                    }
                }
            }
        </div>*@
    </div>
</div>

DAN/DAN/DAN/Views/Order/ReturnVNPay.cshtml
@model DAN.Models.Order

@{
    ViewBag.Title = "Hoàn thành đặt hàng";
}
@if (@Model.OId.Length > 0)
{
    <div class="container">
        <div class="row info">
            <div class="checkout">
                <div class="confirm">
                    Cảm ơn bạn đã đặt hàng. Mã đơn hàng của bạn là <b>@Model.OId</b><br />
                    Kiểm tra đơn hàng của bạn tại: <a href="http://localhost:49278/Order/SearchInvoice">Đây</a><br />
                    Bạn có thể liên hệ hotline: <b>0354122468</b> để chúng tôi duyệt đơn hàng cho bạn sớm nhất có thể.<br />
                    Xin cảm ơn!
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="row info">
            <div class="checkout">
                <div class="confirm">
                    Thanh toán không thành công <br />
                    <b></b><br />
                    Quay về trang chủ tại: <a href="http://localhost:49278">Đây</a><br />
                    Bạn có thể liên hệ hotline: <b>0354122468</b> để chúng tôi hỗ trợ cho bạn sớm nhất có thể.<br />
                    Xin cảm ơn!
                </div>
            </div>
        </div>
    </div>
}

DAN/DAN/DAN/Views/Order/SearchInvoice.cshtml
@model DAN.Models.SearchInvoiceModel
@{
    ViewBag.Title = "Tìm kiếm đơn hàng";
}
<div class="container">
    <div class="row info">
        <div class="title">Tìm kiếm đơn hàng</div>
        <center>
            @using (Html.BeginForm("SearchInvoice", "Order", FormMethod.Post, new { @class = "my-form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.LabelFor(e => e.OId)
                @Html.ValidationMessageFor(e => e.OId)
                @Html.TextBoxFor(e => e.OId)
                <button> Tìm kiếm</button>
            }
        </center>
    </div>
</div>